### ISSUE TITLE
Error: Cannot find module 'debug'

### ISSUE THREAD

**Issue by DrDaveD** [ben-bradley/leonidas#3]
After getting the three VMs up with the Vagrantfile in PR #2, I continued on to start leonidas with the commands instructed of

```
vagrant ssh router
sudo su -
cd /vagrant
node app.js
```

When I run the latter I get the following output:

```
module.js:471
    throw err;
    ^

Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/vagrant/app.js:8:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

I'm at a loss as to how to figure out how to fix this because I can't even find module.js.   Do you have any hints for me?

**Comment by ben-bradley** [comment]
Hi Dave,

  Try this:

```
vagrant ssh router
sudo su -
cd /vagrant
npm install
node app.js
```

**Comment by DrDaveD** [comment]
@ben-bradley Thanks!  That failed because it couldn't find git, but it worked after I did 'apt-get install git' .   Then I could also do the snmpget from the poller (adding one to the IP address since I changed it).

Now I can continue my investigation.
